/*
 * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// -----------------------------------------------------
// NOTE: THIS HEADER IS ALSO INCLUDED BY ASSEMBLER SO
//       SHOULD ONLY CONSIST OF PREPROCESSOR DIRECTIVES
// -----------------------------------------------------

// This header may be included by other board headers as "boards/pico.h"

#ifndef _BOARDS_SDUINO_H
#define _BOARDS_SDUINO_H

// For board detection
#define RASPBERRYPI_SDUINO

// --- UART ---
#ifndef PICO_DEFAULT_UART
#define PICO_DEFAULT_UART 0
#endif
#ifndef PICO_DEFAULT_UART_TX_PIN
#define PICO_DEFAULT_UART_TX_PIN 12
#endif
#ifndef PICO_DEFAULT_UART_RX_PIN
#define PICO_DEFAULT_UART_RX_PIN 13
#endif

// --- LED ---
#ifndef PICO_DEFAULT_LED_PIN
#define PICO_DEFAULT_LED_PIN 0
#endif

// --- I2C ---
#ifndef PICO_DEFAULT_I2C
#define PICO_DEFAULT_I2C 1
#endif
#ifndef PICO_DEFAULT_I2C_SDA_PIN
#define PICO_DEFAULT_I2C_SDA_PIN 10
#endif
#ifndef PICO_DEFAULT_I2C_SCL_PIN
#define PICO_DEFAULT_I2C_SCL_PIN 11
#endif

// --- SPI ---

#ifndef PICO_DEFAULT_SPI
#define PICO_DEFAULT_SPI 0
#endif
#ifndef PICO_DEFAULT_SPI_SCK_PIN
#define PICO_DEFAULT_SPI_SCK_PIN 6
#endif
#ifndef PICO_DEFAULT_SPI_TX_PIN
#define PICO_DEFAULT_SPI_TX_PIN 3
#endif
#ifndef PICO_DEFAULT_SPI_RX_PIN
#define PICO_DEFAULT_SPI_RX_PIN 4
#endif
#ifndef PICO_DEFAULT_SPI_CSN_PIN
#define PICO_DEFAULT_SPI_CSN_PIN 5
#endif

// --- SDUINO BOARD INTERNAL PERIPHERALS ---

#ifndef SDUINO_INTERNAL_LED_PIN
#define SDUINO_INTERNAL_LED_PIN 0
#endif

#ifndef SDUINO_INTERNAL_UART
#define SDUINO_INTERNAL_UART 0
#endif
#ifndef SDUINO_INTERNAL_UART_TX_PIN
#define SDUINO_INTERNAL_UART_TX_PIN 12
#endif
#ifndef SDUINO_INTERNAL_UART_RX_PIN
#define SDUINO_INTERNAL_UART_RX_PIN 13
#endif

#ifndef SDUINO_INTERNAL_ESP32_UART
#define SDUINO_INTERNAL_ESP32_UART SDUINO_INTERNAL_UART
#endif

#if !defined(SDUINO_INTERNAL_UART_INSTANCE) && defined(SDUINO_INTERNAL_UART)
#define SDUINO_INTERNAL_UART_INSTANCE (__CONCAT(uart,SDUINO_INTERNAL_UART))
#endif
#ifdef SDUINO_INTERNAL_UART_INSTANCE
#define uart_internal SDUINO_INTERNAL_UART_INSTANCE
#endif

#ifndef SDUINO_INTERNAL_I2C
#define SDUINO_INTERNAL_I2C 1
#endif
#if !defined(SDUINO_INTERNAL_I2C_INSTANCE) && defined(SDUINO_INTERNAL_I2C)
#define SDUINO_INTERNAL_I2C_INSTANCE (__CONCAT(i2c,SDUINO_INTERNAL_I2C))
#endif
#ifdef SDUINO_INTERNAL_I2C_INSTANCE
#define i2c_internal SDUINO_INTERNAL_I2C_INSTANCE
#endif
#ifndef SDUINO_INTERNAL_I2C_SDA_PIN
#define SDUINO_INTERNAL_I2C_SDA_PIN 10
#endif
#ifndef SDUINO_INTERNAL_I2C_SCL_PIN
#define SDUINO_INTERNAL_I2C_SCL_PIN 11
#endif

#ifndef SDUINO_INTERNAL_MAG_I2C
#define SDUINO_INTERNAL_MAG_I2C SDUINO_INTERNAL_I2C
#endif
#if !defined(SDUINO_INTERNAL_MAG_I2C_INSTANCE) && defined(SDUINO_INTERNAL_I2C)
#define SDUINO_INTERNAL_MAG_I2C_INSTANCE (__CONCAT(i2c,SDUINO_INTERNAL_I2C))
#endif

#ifndef SDUINO_INTERNAL_SPI
#define SDUINO_INTERNAL_SPI 0
#endif
#if !defined(SDUINO_INTERNAL_SPI_INSTANCE) && defined(SDUINO_INTERNAL_SPI)
#define SDUINO_INTERNAL_SPI_INSTANCE (__CONCAT(spi,SDUINO_INTERNAL_SPI))
#endif
#ifdef SDUINO_INTERNAL_SPI_INSTANCE
#define spi_internal SDUINO_INTERNAL_SPI_INSTANCE
#endif
#ifndef SDUINO_INTERNAL_SPI_SCK_PIN
#define SDUINO_INTERNAL_SPI_SCK_PIN 18
#endif
#ifndef SDUINO_INTERNAL_SPI_TX_PIN
#define SDUINO_INTERNAL_SPI_TX_PIN 19
#endif
#ifndef SDUINO_INTERNAL_SPI_RX_PIN
#define SDUINO_INTERNAL_SPI_RX_PIN 20
#endif
#ifndef SDUINO_INTERNAL_SPI_CS0_PIN
#define SDUINO_INTERNAL_SPI_CS0_PIN 17
#endif
#ifndef SDUINO_INTERNAL_SPI_CS1_PIN
#define SDUINO_INTERNAL_SPI_CS1_PIN 21
#endif
#ifndef SDUINO_INTERNAL_SPI_CS2_PIN
#define SDUINO_INTERNAL_SPI_CS2_PIN 22
#endif

#ifndef SDUINO_INTERNAL_IMU_SPI
#define SDUINO_INTERNAL_IMU_SPI SDUINO_INTERNAL_SPI
#endif
#if !defined(SDUINO_INTERNAL_IMU_SPI_INSTANCE) && defined(SDUINO_INTERNAL_SPI)
#define SDUINO_INTERNAL_IMU_SPI_INSTANCE (__CONCAT(spi,SDUINO_INTERNAL_SPI))
#endif

#ifndef SDUINO_INTERNAL_IMU_GYRO_CS_PIN
#define SDUINO_INTERNAL_IMU_GYRO_CS_PIN SDUINO_INTERNAL_SPI_CS0_PIN
#endif
#ifndef SDUINO_INTERNAL_IMU_ACCEL_CS_PIN
#define SDUINO_INTERNAL_IMU_ACCEL_CS_PIN SDUINO_INTERNAL_SPI_CS1_PIN
#endif
#ifndef SDUINO_INTERNAL_BMP_CS_PIN
#define SDUINO_INTERNAL_BMP_CS_PIN SDUINO_INTERNAL_SPI_CS2_PIN
#endif

#ifndef SDUINO_INTERNAL_BMP_INT_PIN
#define SDUINO_INTERNAL_BMP_INT_PIN 7
#endif
#ifndef SDUINO_INTERNAL_IMU_INT_PIN
#define SDUINO_INTERNAL_IMU_INT_PIN 16
#endif

#ifndef SDUINO_INTERNAL_DRV_A_IN1_PIN
#define SDUINO_INTERNAL_DRV_A_IN1_PIN 15
#endif
#ifndef SDUINO_INTERNAL_DRV_B_IN1_PIN
#define SDUINO_INTERNAL_DRV_B_IN1_PIN 14
#endif

#ifndef SDUINO_INTERNAL_DRV_A_IN2_PIN
#define SDUINO_INTERNAL_DRV_A_IN2_PIN 9
#endif
#ifndef SDUINO_INTERNAL_DRV_B_IN2_PIN
#define SDUINO_INTERNAL_DRV_B_IN2_PIN 8
#endif

#ifndef SDUINO_INTERNAL_AIN_PIN
#define SDUINO_INTERNAL_AIN_PIN 29
#endif

#ifndef SDUINO_INTERNAL_DRV_VFB_PIN
#define SDUINO_INTERNAL_DRV_VFB_PIN 28
#endif

#ifndef SDUINO_INTERNAL_DRV_A_CFB_PIN
#define SDUINO_INTERNAL_DRV_A_CFB_PIN 27
#endif

#ifndef SDUINO_INTERNAL_DRV_B_CFB_PIN
#define SDUINO_INTERNAL_DRV_B_CFB_PIN 26
#endif



// --- FLASH ---

#define PICO_BOOT_STAGE2_CHOOSE_W25Q080 1

#ifndef PICO_FLASH_SPI_CLKDIV
#define PICO_FLASH_SPI_CLKDIV 2
#endif

#ifndef PICO_FLASH_SIZE_BYTES
#define PICO_FLASH_SIZE_BYTES (16 * 1024 * 1024)
#endif

#ifndef PICO_RP2040_B0_SUPPORTED
#define PICO_RP2040_B0_SUPPORTED 1
#endif

#endif
